[Group 6] Create register screen
tryber/sd-010-a-project-delivery-app pull request #147
Opened 2021-11-12 17:25 UTC by mallmann02

2021-11-13 17:29 UTC, o-flores commented on front-end/src/utils/validateRegisterInputs.js
> +export default function validateRegisterInputs({ name, email, password }) {
Leo, nesse caso a unica função que está sendo usada neste arquivo é a validateRegisterInputs, certo? Pois as verificações de regex, nome e senha tão sendo feitas no proprio componente SignUp.

2021-11-13 17:30 UTC, o-flores requested changes
Fala leo, so fiz um comentário no validateRegisterInputs!

2021-11-13 20:32 UTC, mallmann02 commented on front-end/src/utils/validateRegisterInputs.js
> +export default function validateRegisterInputs({ name, email, password }) {
Sim, porém a função que está sendo exportada depende dessas que estão neste arquivo, não é?

2021-11-16 17:35 UTC, MarcioFujita approved these changes

2021-11-16 17:36 UTC, o-flores approved these changes

2021-11-16 17:37 UTC, merged