[Grupo 10] (Back-end) Sequelize
tryber/sd-010-a-project-delivery-app pull request #40
Opened 2021-11-10 15:08 UTC by TiagoEmanuel8

Configura o sequelize da aplicação com as migrations e as models, além disso faz os devidos relacionamentos entre as tabelas **users**, **products**, **sales** e **salesProducts**, baseado no modelo proposto pelo **readme** do projeto.

Atividades:

- [ ] Configura a **migration** e a **model** da tabela `users`
- [ ] Configura a **migration** e a **model** da tabela `products`
- [ ] Configura a **migration** e a **model** da tabela `sales`
- [ ] Configura a **migration** e a **model** da tabela `salesProducts`
- [ ] Faz o relacionamento entra tabelas conforme o readme do projeto

2021-11-10 15:56 UTC, nascjoao requested changes
Boa, pessoal! 

Comecei a fazer algumas sugestões de alteração ali na _migration_ de _users_, mas creio que o ideal seja alterar nos _models_, né?
As sugestões que fiz a _users_ eu estendo às outras tabelas, para prevenirmos que dados sejam registrados em `null`.

Por exemplo, em `price`, o ideal seria que somente `url_image` não recebesse `allowNull: false`, e `createdAt` receberia o `defaultValue: Sequelize.NOW`. Vale verificar todos os models e ver onde essas ideias se aplicam.

Podemos fazer isso e gerar novamente as _migrations_?

Não vejo erros, mas eu sugiro essas alterações para evitar futuros problemas como registros _null_ e data de criação sendo submetida pelo _frontend_.

2021-11-10 15:56 UTC, nascjoao commented on back-end/src/database/config/config.js
> +console.log('teste', process.env.MYSQL_DB_NAME);
Podemos tirar esse log?
```suggestion
```

2021-11-10 15:56 UTC, nascjoao commented on back-end/src/database/migrations/20211110000658-create-users.js
> +        type: Sequelize.STRING
Creio que aqui, e também nas colunas de e-mail e password, seria melhor não permitirmos o registro `null`, certo?
```suggestion
        type: Sequelize.STRING,
        allowNull: false
```

2021-11-10 15:56 UTC, nascjoao commented on back-end/src/database/migrations/20211110000658-create-users.js
> +        type: Sequelize.STRING
```suggestion
        type: Sequelize.STRING,
        allowNull: false
```

2021-11-10 15:56 UTC, nascjoao commented on back-end/src/database/migrations/20211110000658-create-users.js
> +        type: Sequelize.STRING
O [requisito 40](https://github.com/tryber/sd-010-a-project-delivery-app#40---desenvolva-a-tela-da-pessoa-administradora-de-forma-a-validar-o-formul%C3%A1rio-de-cadastro) do projeto sugere que a `role` tenha um valor _default_. Poderíamos colocar algo como `customer`? Estou levando em consideração que o projeto usa os termos `customer`, `seller` e `admin`.
```suggestion
        type: Sequelize.STRING,
        defaultValue: 'customer'
```

2021-11-10 15:56 UTC, nascjoao commented on back-end/src/database/migrations/20211110000658-create-users.js
> +        type: Sequelize.DATE
Aqui é válido a data já entrar automaticamente
```suggestion
        type: Sequelize.DATE,
        defaultValue: Sequelize.NOW
```

2021-11-10 17:04 UTC, TiagoEmanuel8 commented on back-end/src/database/migrations/20211110000658-create-users.js
> +        type: Sequelize.STRING
Concordo, até vai evitar que tenhamos futuros problemas nesse projeto, valeu demais

2021-11-11 20:14 UTC, jonathanjf commented on back-end/src/controller/index.js
> +const user = require('./userController');
opa, seria legal, talvez utilizar o mesmo formato de nomes para os import's

2021-11-11 20:22 UTC, jonathanjf approved these changes

2021-11-11 21:16 UTC, nascjoao approved these changes

2021-11-11 21:17 UTC, merged